from data_types.singly_linked_list import LinkedList

linked_list = LinkedList()
linked_list.append_value(3)
linked_list.prepend_value(2)
linked_list.prepend_value(1)
linked_list.append_value(4)
linked_list.append_value(5)
linked_list.append_value(6)
linked_list.append_value(7)
linked_list.append_value(8)
print("creating singly linked list of length: ", linked_list.length())
print(linked_list)
print("reversing list")
linked_list.revese_list(linked_list.head)
print(linked_list)
print("append 0")
linked_list.append_value(0)
print("prepend 9")
linked_list.prepend_value(9)
print(linked_list)
print("find index of 7 and remove via index")
linked_list.remove_value_at_index(linked_list.find_value_index(7))
print(linked_list)
